### ISSUE TITLE
How to have a pdf version of an article as a link in the article

### ISSUE THREAD

**Issue by robtaylor** [pelican-plugins/pdf#15]
Hi, I'd like to generate a documentation site with pdf versions of each article linked from the html page, is this possible using this plugin? Thanks!

**Comment by wombelix** [comment]
> possible using this plugin?

Not with the plugin directly but the names  are predictable. I add links to the .rst and .pdf files in my template at the end of each article.

Relevant line: https://git.sr.ht/~wombelix/pelican-theme-xlii/tree/main/item/templates/article.html#L77

Example article: https://dominik.wombacher.cc/posts/installing-static-site-generator-pelican-inclusive-plugins-with-pipx.html

**Comment by robtaylor** [comment]
Thank you, that helps a lot!
