### ISSUE TITLE
old version still in pelican-plugins

### ISSUE THREAD

**Issue by robtaylor** [pelican-plugins/pdf#16]
Hi, there's an old version still in pelican-plugins, which makes it difficult if you need to use something from there.
Should it be deleted, or this added as submodule?

**Comment by wombelix** [comment]
Not exactly sure what you mean?

https://github.com/getpelican/pelican-plugins/tree/master/pdf has the following at the top of the readme:
> NOTE: This plugin has been moved to its own repository. Please file any issues/PRs there. Once all plugins have been migrated to the new Pelican Plugins organization, this monolithic repository will be archived.

Which seemed to be the standard way of doing it two years ago, what's wrong with that?

If that make any problems, @justinmayer might know a solution.

**Comment by justinmayer** [comment]
> Should it be deleted, or this added as submodule?

Neither.

Plugins are slowly, one-by-one, being migrated from the legacy monolithic repository to this organization as separate repositories (like this one). Eventually, that legacy monolithic repository will be archived.

What exactly is the difficulty?

**Comment by robtaylor** [comment]
I can't get pelican to use bootstrap-rst from pelican-plugins alongside pdf. I think i'm maybe misunderstanding how to get pelican to use the seperate repo versions?

**Comment by robtaylor** [comment]
i.e. i have `PLUGIN_PATHS` set to a checkout of pelican-plugins, and have `bootstrap-rst` and `pdf` in `PLUGINS`

**Comment by justinmayer** [comment]
The way _I_ would handle that is to:

1. Create a separate folder on your workstation such as `~/Projects/your-site/plugins`
2. Copy the `bootstrap-rst` plugin from your clone of the `pelican-plugins` legacy repo to `~/Projects/your-site/plugins/bootstrap-rst`
3. Set `PLUGIN_PATHS` appropriately (to whatever location you chose for the above plugin folder).
4. Install the PDF plugin from the new repo via: `python -m pip install pelican-pdf`
5. Set: `PLUGINS = ["bootstrap-rst", "pdf"]`
6. Run `pelican-plugins` to confirm that both plugins are registered and active.

**Comment by avaris** [comment]
> I can't get pelican to use bootstrap-rst from pelican-plugins alongside pdf.

Why not? What happens? Namespace plugins should have precedence during loading: i.e. there shouldn't be any issue such as picking the wrong one due to name clashes.

**Comment by robtaylor** [comment]
@justinmayer not an option I'm afraid as I'm using submodules and reproducible out of tree builds
@avaris  with
```
PLUGIN_PATHS = [ 'documentation/pelican-plugins' ]
PLUGINS      = [ 'bootstrap-rst',
                  'pdf']
```
and pelican-plugins checked out at HEAD of main.

I get:
```
[21:31:00] ERROR    Cannot load plugin `pdf`                           log.py:96
                    No module named 'xhtml2pdf'
```

```
% pip show pelican-pdf
Name: pelican-pdf
Version: 1.0.3
Summary: PDF Generator is a Pelican plugin that exports articles and pages as PDF files during site generation
Home-page: https://github.com/pelican-plugins/pdf
Author: Pelican Dev Team
Author-email: authors@getpelican.com
License: AGPL-3.0
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: pelican, rst2pdf, xhtml2pdf
Required-by:% pip show pelican-pdf
Name: pelican-pdf
Version: 1.0.3
Summary: PDF Generator is a Pelican plugin that exports articles and pages as PDF files during site generation
Home-page: https://github.com/pelican-plugins/pdf
Author: Pelican Dev Team
Author-email: authors@getpelican.com
License: AGPL-3.0
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: pelican, rst2pdf, xhtml2pdf
Required-by:`
```
```
$ pip show pelican
Name: pelican
Version: 4.5.4
Summary: Static site generator supporting Markdown and reStructuredText
Home-page: https://getpelican.com
Author: Justin Mayer
Author-email: entrop@gmail.com
License: AGPLv3
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: blinker, docutils, feedgenerator, jinja2, pygments, python-dateutil, pytz, unidecode
Required-by: pelican-pdf
```

**Comment by avaris** [comment]
>                    No module named 'xhtml2pdf'

This suggests you are missing a dependency. Can you show full error traceback by running `pelican` with `--debug`.

> not an option I'm afraid as I'm using submodules and reproducible out of tree builds

There are still ways to accomplish it within that frame:
* add `pelican-plugins` as a submodule
* create a folder (e.g. `active-plugins` or whatever)
* symlink the plugins you use from `pelican-plugins` to `active-plugins`.
* use `active-plugins` in `PLUGIN_PATHS` instead
