### ISSUE TITLE
Weird symbols appearing when creating PDFs from articles with non-ASCII characters

### ISSUE THREAD

**Issue by vlajna95** [pelican-plugins/pdf#6]
I am writing a blog in serbian, and there are weird characters in the resulting PDFs. 

In the article: Šta ćeš sve pročitati

In the PDF: Šta ■eš sve pro■itati 

Is there anything to do to fix this problem?

**Comment by wombelix** [comment]
Hey @vlajna95 thanks for reporting the Issue, let me take a look, seems like an encoding issue at some point.

**Comment by wombelix** [comment]
The Pelican PDF Plugin use `rst2pdf` to generate the PDF output. The Issues you reported isn't a Problem with the Code or some file Encoding as I first thought. 

The white squares get added as fallback when the used Font doesn't know the Characters, in your Example `ć` and `č`.
So using a different Font which is aware off those Characters seem to be the Solution.

I added `PDF_STYLE = 'kerning'` to my `pelicanconf.py` and can now see the actual Characters instead a square, output attached: [test_pdf_rst.pdf](https://github.com/pelican-plugins/pdf/files/7266358/test_pdf_rst.pdf)

More about rst2pdf Styles can be found here: http://rst2pdf.ralsina.me/handbook.html#styles
