### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by nandac** [pelican-plugins/pdf#8]
Dear Folks,

This is not an issue with the plugin but with the documentation.

The text `rst2pdf documentation` in the README points to the link http://rst2pdf.ralsina.me/handbook.html#styles which does not exist.

I think the link should be https://rst2pdf.org/static/manual.html#styles which is the official rst2pdf site as far as I can tell.

**Comment by wombelix** [comment]
Thank you @nandac for reporting the broken link

**Comment by wombelix** [comment]
Fixed with https://github.com/pelican-plugins/pdf/pull/9
